imports:
  - { resource: easyadmin/ }

easy_admin:
  design:
      form_theme:
          - '@EasyAdmin/form/bootstrap_4.html.twig'
          - "@FOSCKEditor/Form/ckeditor_widget.html.twig"


#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
